### ISSUE TITLE
Organization Page: Add Related Content

### ISSUE THREAD

**Issue by lsweltz** [InterActionNGO/ngoaidmap#21]
On the organization page:

- Add a “Related Images” section that displays a list of URLs that link to external images.
- Add a “Related Videos” section that displays a list of URLs that link to external videos.
- Place content in the main content well below other page content but above the featured maps section.

**Comment by RBFraxinus** [comment]
There's already a blueprint for displaying a slideshow of image and video resourced related to a project (https://ngoaidmap.org/projects/18733 for example).  For now, we are imagining the same type of display for related images and videos for organizations.   You can just re-use that code.
