### ISSUE TITLE
Organization Page: Project data does not display

### ISSUE THREAD

**Issue by lsweltz** [InterActionNGO/ngoaidmap#24]
http://ngoaidmap.staging.vigetx.com/organizations/124

- Page shows 0 projects even if projects exist.

**Comment by mzlock** [comment]
Backbone is getting the value 0, so this is a back-end issue.

**Comment by mzlock** [comment]
@brianjlandau - you might want to look in `app/controllers/api/v1/private/private_controller`.  That is what's returning the data to the Backbone app.

**Comment by lsweltz** [comment]
👍
