### ISSUE TITLE
Project Page: International and local partners do not display

### ISSUE THREAD

**Issue by lsweltz** [InterActionNGO/ngoaidmap#25]
http://ngoaidmap.staging.vigetx.com/projects/19265

- No partners display even though 2 international and 2 local partners exist

**Comment by mzlock** [comment]
I'm getting the same thing locally.  The data in `project.partner_organizations` in the Backbone component is null, so I think this is a back-end issue, not front-end.

**Comment by mzlock** [comment]
@brianjlandau - you might want to look in `app/controllers/api/v1/private/private_controller`.  That is what's returning the data to the Backbone app.

**Comment by lsweltz** [comment]
👍
