### ISSUE TITLE
Countries Page: Reporting organizations do not display

### ISSUE THREAD

**Issue by lsweltz** [InterActionNGO/ngoaidmap#27]
http://ngoaidmap.staging.vigetx.com/location/gn_3469034?level=1
- No reporting organizations display in the sidebar

**Comment by lsweltz** [comment]
@mzlock I still don't see the reporting organizations in the sidebar of any of the country pages (but that could be a data error). I see the list of donor organizations but not reporting organizations. Are you seeing this locally?

**Comment by brianjlandau** [comment]
@mzlock Is this something I need to wire up with data from the backend?

**Comment by lsweltz** [comment]
@mzlock @brianjlandau 

Are reporting organizations displayed in the [Some Organizations section](https://www.dropbox.com/s/v77v47zaqg7ut7x/Screenshot%202016-11-03%2017.47.59.png?dl=0) of the sidebar?

The title of that section should be "Reporting Organizations" and if there are more organizations than we want to initially display, we should follow the same behavior pattern as the donors section below it (Include a "See more organizations" link at the bottom of the list and expand the list when clicked).
