### ISSUE TITLE
Organization Page: Update display of content

### ISSUE THREAD

**Issue by lsweltz** [InterActionNGO/ngoaidmap#31]
- Display media at the bottom of the page (below projects)
- Remove "Related Resources" heading
- [Screenshot](https://www.dropbox.com/s/fwvesv5vyx6uklu/Screenshot%202016-09-26%2015.15.05.png?dl=0)

**Comment by brianjlandau** [comment]
@lsweltz @mzlock is this done? Anything I need to do to wrap this up?

**Comment by lsweltz** [comment]
:+1:
