### ISSUE TITLE
Project Page: Display local and international partners as separately

### ISSUE THREAD

**Issue by lsweltz** [InterActionNGO/ngoaidmap#32]
- All organizations with an international organization distinction should display within the international partners section of the projects page.
- All organizations with a local organization distinction will display within the local partners section of the projects page.

Related to: https://github.com/InterActionNGO/NGO-admin/issues/24

**Comment by mzlock** [comment]
Ready for @brianjlandau to take this over.  I updated Backbone to expect different data to separate these.  I believe you just need to update the data model to match what I have. Let me know if this is doable or if I should re-work the JS to match your data model.

Old data:
```
project.partner_organizations: "string - list of partners"
```

New Epected Data:
```
project.partner_organizations: {
    local: [
        "Name of Partner",
        "Name of Partner"
    ],
    international: []
}
```

**Comment by mzlock** [comment]
@brianjlandau - the code I did is in `feature-separate-partners`

**Comment by mzlock** [comment]
@brianjlandau - you might want to look in `app/controllers/api/v1/private/private_controller`.  That is what's returning the data to the Backbone app.

**Comment by lsweltz** [comment]
👍
