### ISSUE TITLE
Update language of the report budget filter summary text

### ISSUE THREAD

**Issue by brianjlandau** [InterActionNGO/ngoaidmap#37]
From Robert:

> The language in the filters applied section is slightly incorrect.  When a value is given for max budget, the wording in the filters says "below", like in the screenshot.  Conversely, when a min budget is given (and no max) is says "above".  Since the filters should include the value itself as well as those above and below, depending on the filter used, the wording should be modified to make this clear.  For instance, "At or below X" for a max filter, and "At or above" for a min filter.  Or, another option: "[value] and above" and "[value] and below".

**Comment by lsweltz** [comment]
:+1:
