### ISSUE TITLE
[Project Form] DEV: Within the admin, forms take too long to load.

### ISSUE THREAD

**Issue by btornes** [InterActionNGO/ngoaidmap#41]
Backend - Project Form] The project forms take a lot longer to load lately and we'd like to pinpoint what the cause is and address it soon if possible. Our first suspicion is possibly the thousands of organizations that are being loaded into the select elements for partners and prime awardees. Your thoughts?

**Comment by brianjlandau** [comment]
Moved to InterActionNGO/NGO-admin#37
