### ISSUE TITLE
[Dashboard] DEV: Headings don't seem to pull in correct numbers

### ISSUE THREAD

**Issue by btornes** [InterActionNGO/ngoaidmap#42]
[Backend - Member dashboard] Looks like the headings for the "Projects ending in ## months" section are not correct. In the member dashboard I viewed, there were two sections, both saying "# projects ending in 3 months", but one had projects ending in 3 months, and the other looked like it should've been labeled 12

**Comment by brianjlandau** [comment]
Moved to InterActionNGO/NGO-admin#36
