### ISSUE TITLE
[Organization Budget] DEV: Budget displayed should be converted

### ISSUE THREAD

**Issue by btornes** [InterActionNGO/ngoaidmap#46]
[Front End - Organization Budget] The organization page annual budgets are always displaying the unconverted budget value and currency. This should only be the behavior when a given currency is unsupported and no converted value exists. When a supported currency is converted, it should show the USD value, similar to the way project budgets are displayed, noting near the value that it was converted from X currency.

**Comment by mzlock** [comment]
@brianjlandau - is there any FED involved in this or is this all back-end?

**Comment by brianjlandau** [comment]
This was all dev, and is completed.

**Comment by btornes** [comment]
@brianjlandau Can we remove the "Converted from USD" when the budget was entered as USD?

**Comment by brianjlandau** [comment]
Fixed and deployed

**Comment by btornes** [comment]
@brianjlandau hmm, looks like they are now back to not showing the USD conversion. In my example organization (http://office.ngoaidmap.staging.vigetx.com/admin/organizations/124/edit), I put in Mexican Pesos (which previously had been converted) and it looks like: http://ngoaidmap.staging.vigetx.com/organizations/124

**Comment by brianjlandau** [comment]
This is because the `budget_fiscal_year` is set to `1972-03-04` the data set we use doesn't go back that far. Pick a more recent date, maybe last 10 years?
