### ISSUE TITLE
[Banner Menu] FED: Menu items not displaying correctly

### ISSUE THREAD

**Issue by btornes** [InterActionNGO/ngoaidmap#53]
[Front End - Banner Menu] The menu items under the map stack up over one another when clicked. Can you make the click of one menu item hide whatever is currently up, ensuring only one menu is visible at a time?

**Comment by btornes** [comment]
Robert's comment - can you update based on whichever of his solutions is easier?:
The behavior is better, though still a bit awkward, due to the overlapping.  The menus to the right are "above" the menus on the left, so if you click one and then hover over the one left of it, the hovered one is half-covered by the clicked-open one.  

Not sure I have a preference between:
 - unshowing the clicked-open menu by click & by mouseover
 - ensuring that mouseover-showing menus have a higher z-index so they're not covered by a clicked menu on their right

**Comment by mzlock** [comment]
@btornes - merged a change, bit this will need to be deployed before I can mark this as ready to be deployed.  And I believe @brianjlandau might need to be the one to deploy.

**Comment by btornes** [comment]
As discussed in Slack - Megan will try to make an update so the focus state that is initiated when someone clicks on a menu goes away if they hover to a new menu item.

**Comment by btornes** [comment]
![Menu Click Focus](http://g.recordit.co/H7PJgEUC3N.gif)

**Comment by mzlock** [comment]
@btornes I still haven't addressed that outline just yet -- the bit of code merged there solves a different issue reported in Basecamp

**Comment by mzlock** [comment]
@btornes - fix on that lat item added.  Can you have @brianjlandau deploy to staging so the fix can be QAed and confirmed?

**Comment by brianjlandau** [comment]
Deployed!

**Comment by btornes** [comment]
This looks good on staging! @brianjlandau Can you push to production?

**Comment by brianjlandau** [comment]
Deploying now!
