### ISSUE TITLE
[Reports] Certain reports are failing to load any results

### ISSUE THREAD

**Issue by RBFraxinus** [InterActionNGO/ngoaidmap#69]
The culprit seems to be the use of the "active" checkbox filter.  When it is not checked, the reports seem to be ok, but when it is checked, no results ever get loaded -- just spinning wheel.

**Comment by brianjlandau** [comment]
I can't reproduce this locally or on production. Can you provide more specific details about the conditions to reproduce?

**Comment by RBFraxinus** [comment]
This appears to have resolved mysteriously on its own
